### ISSUE TITLE
preapprovals - not initiating

### ISSUE THREAD

**Issue by nuriel** [adamthedeveloper/wepay-rails#34]
hi, having some trouble with implementing a preapproval, the call:

```
 response      = wepay_gateway.perform_preapproval(checkout_params)
```

 in init_preapproval returns:

```
 undefined method `merge' for nil:NilClass
```

 it works great for checkout.. any ideas?

**Comment by adamthedeveloper** [comment]
I'll look into that and get back to you. Thanks for reporting it.

**Comment by nuriel** [comment]
thank you for the great gem.

let me know if I could help in any way.

**Comment by keenahn** [comment]
Hey @nuriel, not sure if this is still relevant to you. I just started using this gem and ran into the same problem. Most likely, the function is failing because you're either including unrecognized params, or not including all required params. 

https://www.wepay.com/developer/reference/preapproval#create
